config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :people do
    resources :animals
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  validates_presence_of :name, :species

  belongs_to :person
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  #validations
  validates_presence_of :name

  #callbacks
    #after_create - runs once after the model is created
    #before_create - runs once right before creation
    #after_save  - runs each time after the model is saved
    #before_save - runs each time before a model gets saved
    #after_initialize - runs once after a Person.new
    #before_initialize - runs before instance gets created in memory
    #after_validate - runs after all of the validations
    #before_validate - runs before all validations

  #associations
  #has_one
  #has_many
  #belongs_to
  #has_many_through
  #has_one_through
  has_many :animals

  #instance methods
  #def info
  def info
    "#{name} is of age: #{age}"
  end


  #class methods - scopes
  #you could do Person.all.by_name.by_age 
  #def self.info
  #Person.all.by_name
  def self.by_name
    order(:name)
  end

  #Person.all.by_age
  def self.by_age
    order(:age)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, except: [:index, :new, :create]


  def index
    @people = Person.all.by_name
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path(@person)
  end

  private
  def person_params
    params.require(:person).permit(:name, :age, :gender, :alive)
  end

  def set_person
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalsRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_person.html.erb
<%= form_for @person do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>
  <br>
  <%= f.label :age %>:
  <%= f.text_field :age %>
  <br>
  <%= f.label :gender %>:
  <%= f.text_field :gender %>
  <br>
  <%= f.label :alive %>:
  <%= f.radio_button :alive, true %> Yes
  <%= f.radio_button :alive, false %> No
  <br>
  <%= f.submit 'Add Person' %>
<% end %>

app/views/people/edit.html.erb
<h1>Edit <%= @person.name %></h1>
<hr>
<%= render(partial: 'person') %>
<hr>
<%= link_to "Cancel", people_path %>

app/views/people/index.html.erb
<h1>List of People</h1>
<hr>

<ul>
  <% @people.each do |person| %>
    <li>
      <%= person.name %> --
      <%= link_to 'View', person_path(person) %> |
      <%= link_to 'Edit', edit_person_path(person) %> |
      <%= link_to 'Delete', person_path(person), method: :delete, data: {confirm: 'Do you want to delete this person?'} %>
    </li>
  <% end %>
</ul>

<hr>
<%= link_to 'Add Person', new_person_path %>

app/views/people/new.html.erb
<h1>Add Person</h1>

<%= render(partial: 'person') %>
<hr>
<%= link_to "Cancel", people_path %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<hr>

<div>
  <% if @person.age %>
    <p>Age: <%= @person.age %></p>
  <% end %>
  <% if @person.gender %>
    <p>Gender: <%= @person.gender %></p>
  <% end %>
    <p>Alive: <%= @person.alive ? 'Yes' : 'No' %></p>
</div>
<hr>
<%= link_to "Back", people_path %>